# Generated by Django 4.2.2 on 2023-10-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("esthertrade", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delivery_amount",
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_fee",
            field=models.DecimalField(decimal_places=2, default=450.0, max_digits=8),
        ),
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.EmailField(default="example@example.com", max_length=254),
        ),
    ]
