# Generated by Django 4.2.2 on 2023-10-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "esthertrade",
            "0002_remove_order_delivery_amount_order_delivery_fee_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(
                through="esthertrade.OrderItem", to="esthertrade.commodity"
            ),
        ),
        migrations.AlterField(
            model_name="commodity",
            name="image",
            field=models.ImageField(upload_to="commodities/"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
