# Generated by Django 4.2.2 on 2023-10-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("esthertrade", "0003_order_items_alter_commodity_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="item_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
