# Generated by Django 4.2.2 on 2023-10-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("esthertrade", "0004_alter_orderitem_item_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commodity",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
