# Generated by Django 4.2.2 on 2023-10-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("esthertrade", "0006_alter_commodity_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
